# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1
  # aws-cli: circleci/aws-cli@4.1.0
  # docker: circleci/docker@2.2.0
  # minikube: takescoop/minikube@1.0.1

# commands:
#   destroy-infra:
#     description: destroys terraform infrastructure
#     steps:
#       - run:
#           name: Destroy environment
#           when: on_fail
#           command: |
#             terraform destroy

jobs:
  deploy-infra:
    - add_ssh_keys:
        fingerprints: ["56:63:f5:1d:7c:df:61:70:19:79:82:96:d2:1b:ae:c7"]
    executor: terraform/default
    steps:
      - checkout
      # - terraform/init:
      #     path: main
      # - terraform/validate:
      #     path: main
      # - terraform/plan:
      #     path: main
      #     persist-workspace: true
      # - terraform/apply:
      #     path: main
      #     attach-workspace: true
      - terraform/destroy:
          path: main
      # - destroy-infra
    # working_directory: /terraform
  # delete-infrastructure:
  #   executor: terraform/default
  #   steps:
  #     - checkout
  #     - terraform/destroy:
          # path: main

#   example-job:
#     docker:
#       # replace with your preferred image
#       - image: cimg/base:stable
#     steps:
#       - docker/install-docker
#       - docker/dockerlint
#       - docker/pull
#       - docker/configure-docker-credentials-store

#   example-job1:
#     docker:
#       # replace with your preferred image
#       - image: cimg/base:stable
#     steps:
#       - minikube/install-kubectl
#       - minikube/install
#       - minikube/start

workflows:
  deploy-infra:
    jobs:
    - deploy-infra
    # - terraform/validate:
    #     checkout: true
    #     context: terraform
    # - terraform/plan:
    #     checkout: true
    #     context: terraform
    #     persist-workspace: true
    #     requires:
    #     - terraform/validate
    # - terraform/apply:
    #     attach-workspace: true
    #     context: terraform
    #     requires:
    #     - terraform/plan