# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1
  # aws-cli: circleci/aws-cli@4.1.0
  # docker: circleci/docker@2.2.0
  # minikube: takescoop/minikube@1.0.1

jobs:
  deploy-infra:
    executor: terraform/default
    working_directory: ~/web/terraform
    steps:
      - checkout
      - terraform/init:
          path: ~/web/terraform
      - terraform/validate:
          path: ~/web/terraform
      - terraform/plan:
          path: ~/web/terraform
      - terraform/apply:
          path: ~/web/terraform

  # delete-infrastructure:
  #   executor: terraform/default
  #   steps:
  #     - checkout
  #     - terraform/destroy:
  #         path: .

#   example-job:
#     docker:
#       # replace with your preferred image
#       - image: cimg/base:stable
#     steps:
#       - docker/install-docker
#       - docker/dockerlint
#       - docker/pull
#       - docker/configure-docker-credentials-store

#   example-job1:
#     docker:
#       # replace with your preferred image
#       - image: cimg/base:stable
#     steps:
#       - minikube/install-kubectl
#       - minikube/install
#       - minikube/start

workflows:
  deploy-infratructure:
    jobs:
    - deploy-infra
    # - terraform/validate:
    #     checkout: true
    #     context: terraform
    # - terraform/plan:
    #     checkout: true
    #     context: terraform
    #     persist-workspace: true
    #     requires:
    #     - terraform/validate
    # - terraform/apply:
    #     attach-workspace: true
    #     context: terraform
    #     requires:
    #     - terraform/plan